### PR TITLE
passes filter results to backend + changes to http call

### LINKED ISSUE #8: Implement filtering options on the backend
Update the food desert algorithm to take into account filtering options entered by the user

Not fully complete, but basic functions of each filtering option. 

**The front end will show what the backend tells it to. The integration with the google maps AP should be calculated on the backend.

### LINKED ISSUE #12: Calculate whether a user is in a food desert
As a user, I want to determine whether my address/home corresponds to a food desert so that I can take concrete steps to deal with food insecurity.

Scenario A: The user’s address is in a food desert
Given: the user has provided their location and clicked Submit
When: the application determines that the user lives in a food desert
Then: the application shows a screen to the user telling them that they live in a food desert

Scenario B: The user’s address is not in a food desert
Given: the user has provided their location and clicked Submit
When: the application determines that the user does not live in a food desert
Then: the application shows a screen to the user telling them that they do not live in a food desert

Scenario C: The application cannot determine if a user lives in a food desert
Given: the user has provided their location and clicked Submit
When: the application is unable to determine whether the user lives in a food desert
Then: the application shows an error explaining that it cannot determine whether the user lives in a food desert

### LINKED ISSUE #83: Styling for results page

### LINKED ISSUE #84: Styling for map view

### PR DESCRIPTION
**Pull request by hannahli23**
Changes
----
- Changed backend algo to encompass more grocery stores
- Passed in filter parameters to backend and included them in algorithm
- Integrated MapContainer into wizard
- Added results screen

Resolved issues
-----

Closes #83 
Closes #84 
Closes #8 
Closes #12

### CODE REVIEW

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Files in the [`client`](/client) directory were modified; please update the client version.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Files in the [`server`](/server) directory were modified; please update the server version.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 44f5fd1152f093889b8777152a52c1599ba098cb
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Files in the [`server`](/server) directory were modified; please update the server version.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f0df4c234595d26fb4bf47134d3e98c4250fa5ea
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dca4a59e3075cf6f44fca34269f84767bdde70cd
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4e376368c266bb8462d6e76adda0d1dcc7918913
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 02405badd446d9f6c5d34821fda2f7a6a5942bc4
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 317807fc568244ed32758a4aaadbfabf9d9a4ca6
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 354e15e68c6b83fce506e1721623b0416d97077a
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d44ea748977228feacc8958ef654e09d497fd0ce
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1e26899f1a9c5ac757500572d23f6367dab4178c
</p>

**Review by evan10s — APPROVED** [review]

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 234ced1e265cfe9e175cb731b61abf8b9356621b
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 234ced1e265cfe9e175cb731b61abf8b9356621b
</p>

**Pull request merged**
