### PR TITLE
Lots of continuous integration love

### LINKED ISSUE #20: Create CI pipeline for automated deployment
Creating continuous integration pipeline. 
I.e pull request checks 

Acceptance criteria:
- When you push to master, the build is automatically deployed to staging
- There is a way to promote a build to production
- If a build fails, there is a failing pull request check

### LINKED ISSUE #33: Code style and automatic dependency update checks
Add two more integrations to the repo to accomplish the following:

1. Automatically check for code style problems on pull requests
2. Automatically create pull requests (and ideally merge them if CI checks pass) for dependencies that can be updated

### LINKED ISSUE #34: Add a pull request template

### PR DESCRIPTION
**Pull request by evan10s**
- Adds a dependabot config to automerge safe dependency updates (to our staging build, so it'll always still have to be manually promoted to production)
- Added a pull request template
- Added dangerJS to run some automated sanity checks on PRs
- Configured heroku staging and production builds with automated review apps

Closes #34 
Closes #33 
Closes #20

### CODE REVIEW

**Comment by evan10s** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>The client files were modified; please update the client version.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>triangular_flag_on_post</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 10ced41eaafda5c0aaaadb03e9f2071d388b6eb1
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Files in the [`client`](/client) directory were modified; please update the client version.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request includes dependency changes in the root `package.json`.  Is this intentional?
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>🚩</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0d10ef29763381a4ec672ef75cdf654dea123889
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>

## Error ReferenceError
```
ℹ is not defined
ReferenceError: ℹ is not defined
    at Object.<anonymous> (dangerfile.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.requireFromString [as default] (/home/runner/work/food-deserts/food-deserts/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/runner/work/food-deserts/food-deserts/node_modules/danger/distribution/runner/runners/inline.js:144:63)
    at step (/home/runner/work/food-deserts/food-deserts/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/runner/work/food-deserts/food-deserts/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/runner/work/food-deserts/food-deserts/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/food-deserts/food-deserts/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at exports.runDangerfileEnvironment (/home/runner/work/food-deserts/food-deserts/node_modules/danger/distribution/runner/runners/inline.js:105:136)
```
### Dangerfile
```
15|                 message("This pull request includes client dependency changes.", {icon: ""})
16|             }
17|         }
18|     }));
19| }
---^
20| ℹ;
21| 
22| const server = danger.git.fileMatch("server/**");
23| if (server.edited) {
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bb503e3d14bd18146404325c72c1d82fdf3b5caf
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request includes dependency changes in the root `package.json`.  Is this intentional?
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 62e60c8add83ac4d40aed4661316f4642573810f
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request includes dependency changes in the root `package.json`.  Is this intentional?
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7991aa112a8056e52f4de06322b78bdef1116e9f
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request includes dependency changes in the root `package.json`.  Is this intentional?
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7991aa112a8056e52f4de06322b78bdef1116e9f
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request includes dependency changes in the root `package.json`.  Is this intentional?
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7991aa112a8056e52f4de06322b78bdef1116e9f
</p>

**Comment by 9353oasis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  This pull request includes dependency changes in the root `package.json`.  Is this intentional?
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b5ec56b4481f108a6aed2885022c7074f162ff0b
</p>

**Review by hannahli23 — APPROVED** [review]

**Pull request merged**
